@startuml
'https://plantuml.com/sequence-diagram

hide circles

class MoviesPage
class MovieDetailsPage
class MovieRatingPage

MovieRatingPage -up-o MovieDetailsPage
MoviesPage o-down- MovieDetailsPage
@enduml
