@startuml
'https://plantuml.com/sequence-diagram

hide circles

class WatchListPage
class MovieDeleteRatingPage
class TvShowsDeleteRatingPage

WatchListPage o-- MovieDeleteRatingPage
WatchListPage o-- TvShowsDeleteRatingPage
@enduml
